#! /usr/pkg/bin/perl -w
#
# A trivial Apache ErrorLog filter intended to strip client IP address
# information out of Apache error messages.  You can find similar scripts
# on the internets.  "|sed -e 'something or other'" might also work, but
# you'd have to get the quoting of shell metacharacters right.  Flushing
# might also not work so well then, so that's why this is done in perl
# here.

use strict;

if (@ARGV != 1) {
	die "I need exactly one argument <output file>";
}

my $in = "/dev/stdin";
my $out = $ARGV[0];

open (IN, "< $in") or die "Failed to open $in for reading: $!\n";
open (OUT, ">> $out") or die "Failed to open $out for writing: $!\n";

# turn on buffer autoflush so tail -f error.log works
my $outf = select(OUT);
$|=1;
select($outf);

while (<IN>) {
	s/ \[client.*\]//;
	print OUT;
}
close (OUT);
